<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE  PeopleGather [
        <!ELEMENT PeopleGather (PeopleManager+)>
        <!ELEMENT PeopleManager (Name,Time,Sci,People)>
        <!ELEMENT Name (#PCDATA)>
        <!ELEMENT Time (#PCDATA)>
        <!ELEMENT Sci (#PCDATA)>
        <!ELEMENT People (#PCDATA)>
        ]>

<PeopleGather>
    <PeopleManager>
        <Name>华劳斯</Name>
        <Time>56</Time>
        <Sci>72</Sci>
        <People>40</People>
    </PeopleManager>
    <PeopleManager>
        <Name>克拉拉</Name>
        <Time>15</Time>
        <Sci>75</Sci>
        <People>78</People>
    </PeopleManager>
    <PeopleManager>
        <Name>杰哥</Name>
        <Time>5</Time>
        <Sci>80</Sci>
        <People>83</People>
    </PeopleManager>
    <PeopleManager>
        <Name>尼姑莱</Name>
        <Time>64</Time>
        <Sci>80</Sci>
        <People>18</People>
    </PeopleManager>
    <PeopleManager>
        <Name>虎克</Name>
        <Time>80</Time>
        <Sci>0</Sci>
        <People>76</People>
    </PeopleManager>
    <PeopleManager>
        <Name>部落尼亚</Name>
        <Time>48</Time>
        <Sci>23</Sci>
        <People>85</People>
    </PeopleManager>
    <PeopleManager>
        <Name>曼娅</Name>
        <Time>66</Time>
        <Sci>60</Sci>
        <People>15</People>
    </PeopleManager>
    <PeopleManager>
        <Name>茶包</Name>
        <Time>10</Time>
        <Sci>58</Sci>
        <People>73</People>
    </PeopleManager>
    <PeopleManager>
        <Name>阿丽娜</Name>
        <Time>54</Time>
        <Sci>16</Sci>
        <People>71</People>
    </PeopleManager>
    <PeopleManager>
        <Name>娜她沙</Name>
        <Time>56</Time>
        <Sci>15</Sci>
        <People>64</People>
    </PeopleManager>
    <PeopleManager>
        <Name>希露瓦</Name>
        <Time>68</Time>
        <Sci>57</Sci>
        <People>10</People>
    </PeopleManager>
    <PeopleManager>
        <Name>帕金丝</Name>
        <Time>42</Time>
        <Sci>22</Sci>
        <People>65</People>
    </PeopleManager>
    <PeopleManager>
        <Name>埃里克</Name>
        <Time>78</Time>
        <Sci>9</Sci>
        <People>39</People>
    </PeopleManager>
    <PeopleManager>
        <Name>哥弟</Name>
        <Time>10</Time>
        <Sci>66</Sci>
        <People>50</People>
    </PeopleManager>
    <PeopleManager>
        <Name>肥多了</Name>
        <Time>63</Time>
        <Sci>0</Sci>
        <People>63</People>
    </PeopleManager>
    <PeopleManager>
        <Name>匹克</Name>
        <Time>44</Time>
        <Sci>54</Sci>
        <People>10</People>
    </PeopleManager>
    <PeopleManager>
        <Name>鸡儿波特</Name>
        <Time>36</Time>
        <Sci>40</Sci>
        <People>20</People>
    </PeopleManager>
    <PeopleManager>
        <Name>莉拉</Name>
        <Time>52</Time>
        <Sci>14</Sci>
        <People>30</People>
    </PeopleManager>
    <PeopleManager>
        <Name>菲斯曼</Name>
        <Time>50</Time>
        <Sci>29</Sci>
        <People>17</People>
    </PeopleManager>
    <PeopleManager>
        <Name>佩拉</Name>
        <Time>30</Time>
        <Sci>30</Sci>
        <People>30</People>
    </PeopleManager>
    <PeopleManager>
        <Name>伊离丝</Name>
        <Time>94</Time>
        <Sci>86</Sci>
        <People>0</People>
    </PeopleManager>
    <PeopleManager>
        <Name>邓恩</Name>
        <Time>64</Time>
        <Sci>20</Sci>
        <People>78</People>
    </PeopleManager>
    <PeopleManager>
        <Name>老歌德</Name>
        <Time>12</Time>
        <Sci>62</Sci>
        <People>88</People>
    </PeopleManager>
    <PeopleManager>
        <Name>寒腿鼠鼠</Name>
        <Time>93</Time>
        <Sci>93</Sci>
        <People>0</People>
    </PeopleManager>
    <PeopleManager>
        <Name>奥列格</Name>
        <Time>18</Time>
        <Sci>80</Sci>
        <People>82</People>
    </PeopleManager>
    <PeopleManager>
        <Name>史瓦罗</Name>
        <Time>60</Time>
        <Sci>32</Sci>
        <People>88</People>
    </PeopleManager>
    <PeopleManager>
        <Name>希尔</Name>
        <Time>88</Time>
        <Sci>72</Sci>
        <People>26</People>
    </PeopleManager>
</PeopleGather>