=== MixJade/JavaLearn/codeLearning/src/main/resources/someUtils/quizQuest.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
    限制xml中，
    有一个根标签QuizQuest，
    根标签下，有许多Option标签，
    每个Option标签下，有五个标签：
    分别是:Question、A、AType、B、BTYpe,
    限制<AType>与<BType>标签中，只能有一个英文大写字母，且只能是F、N、M、J中的一个
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="QuizQuest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Option" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Question" type="xs:string"/>
                            <xs:element name="A" type="xs:string"/>
                            <xs:element name="AType">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:length value="1"/>
                                        <xs:enumeration value="E"/>
                                        <xs:enumeration value="I"/>
                                        <xs:enumeration value="S"/>
                                        <xs:enumeration value="N"/>
                                        <xs:enumeration value="T"/>
                                        <xs:enumeration value="F"/>
                                        <xs:enumeration value="J"/>
                                        <xs:enumeration value="P"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="B" type="xs:string"/>
                            <xs:element name="BType">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:length value="1"/>
                                        <xs:enumeration value="E"/>
                                        <xs:enumeration value="I"/>
                                        <xs:enumeration value="S"/>
                                        <xs:enumeration value="N"/>
                                        <xs:enumeration value="T"/>
                                        <xs:enumeration value="F"/>
                                        <xs:enumeration value="J"/>
                                        <xs:enumeration value="P"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MixJade/JavaLearn/codeLearning/src/main/resources/someUtils/quizQuest.xml
<?xml version="1.0" encoding="UTF-8" ?>
<QuizQuest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="quizQuest.xsd">
    <Option>
        <Question>1.当你要外出一整天，你会</Question>
        <A>A.计划你要做什么和在什么时候做</A>
        <AType>J</AType>
        <B>B.说去就去</B>
        <BType>P</BType>
    </Option>
    <Option>
        <Question>2.你是否</Question>
        <A>A.容易让人了解</A>
        <AType>E</AType>
        <B>B.难于让人了解</B>
        <BType>I</BType>
    </Option>
    <Option>
        <Question>3.你认为自己是一个</Question>
        <A>A.较为随兴所至的人</A>
        <AType>P</AType>
        <B>B.较为有条理的人</B>
        <BType>J</BType>
    </Option>
    <Option>
        <Question>4.假如你是一位老师，你会选教</Question>
        <A>A.以事实为主的课程</A>
        <AType>S</AType>
        <B>B.涉及理论的课程</B>
        <BType>N</BType>
    </Option>
    <Option>
        <Question>5.处理许多事情上，你会喜欢</Question>
        <A>A.凭兴所至行事</A>
        <AType>P</AType>
        <B>B.按照计划行事</B>
        <BType>J</BType>
    </Option>
    <Option>
        <Question>6.下面哪个词语更和我心意</Question>
        <A>A.仁慈慷慨的</A>
        <AType>F</AType>
        <B>B.意志坚定的</B>
        <BType>T</BType>
    </Option>
    <Option>
        <Question>7.按照程序表做事，</Question>
        <A>A.合你心意</A>
        <AType>J</AType>
        <B>B.令你感到束缚</B>
        <BType>P</BType>
    </Option>
    <Option>
        <Question>8.你做事多数是</Question>
        <A>A.按当天心情去做</A>
        <AType>J</AType>
        <B>B.照拟好的程序表去做</B>
        <BType>P</BType>
    </Option>
    <Option>
        <Question>9.你倾向</Question>
        <A>A.重视感情多于逻辑</A>
        <AType>F</AType>
        <B>B.重视逻辑多于感情</B>
        <BType>T</BType>
    </Option>
    <Option>
        <Question>10.与很多人一起会</Question>
        <A>A.令你活力培增</A>
        <AType>E</AType>
        <B>B.常常令你心力憔悴</B>
        <BType>I</BType>
    </Option>
    <Option>
        <Question>11.当你有一份特别的任务，你会喜欢</Question>
        <A>A.开始前小心组织计划</A>
        <AType>J</AType>
        <B>B.边做边找须做什么</B>
        <BType>P</BType>
    </Option>
    <Option>
        <Question>12.在大多数情况下，你会选择</Question>
        <A>A.顺其自然</A>
        <AType>P</AType>
        <B>B.按程序表做事</B>
        <BType>J</BType>
    </Option>
    <Option>
        <Question>13.你通常</Question>
        <A>A.与人容易混熟</A>
        <AType>E</AType>
        <B>B.比较沉静或矜持</B>
        <BType>I</BType>
    </Option>
    <Option>
        <Question>14.哪些人会更吸引你？</Question>
        <A>A.一个思想敏捷及非常聪颖的人</A>
        <AType>N</AType>
        <B>B.实事求是，具丰富常识的人</B>
        <BType>S</BType>
    </Option>
    <Option>
        <Question>15.大多数人会说你是一个</Question>
        <A>A.重视自我隐私的人</A>
        <AType>I</AType>
        <B>B.非常坦率开放的人</B>
        <BType>E</BType>
    </Option>
    <Option>
        <Question>16.在一大群人当中，通常是</Question>
        <A>A.你介绍大家认识</A>
        <AType>E</AType>
        <B>B.别人介绍你</B>
        <BType>I</BType>
    </Option>
    <Option>
        <Question>17.哪个是较高的赞誉，或称许为</Question>
        <A>A.能干的</A>
        <AType>T</AType>
        <B>B.富有同情心</B>
        <BType>F</BType>
    </Option>
    <Option>
        <Question>18.你喜欢花很多的时间</Question>
        <A>A.一个人独处</A>
        <AType>I</AType>
        <B>B.合别人在一起</B>
        <BType>E</BType>
    </Option>
    <Option>
        <Question>19.一般来说，你和哪些人比较合得来？</Question>
        <A>A.富于想象力的人</A>
        <AType>N</AType>
        <B>B.现实的人</B>
        <BType>S</BType>
    </Option>
    <Option>
        <Question>20.你宁愿被人认为是一个</Question>
        <A>A.实事求是的人</A>
        <AType>S</AType>
        <B>B.机灵的人</B>
        <BType>N</BType>
    </Option>
    <Option>
        <Question>21.哪个是较高的赞誉，或称许为？</Question>
        <A>A.一贯感性的人</A>
        <AType>F</AType>
        <B>B.一贯理性的人</B>
        <BType>T</BType>
    </Option>
    <Option>
        <Question>22.你会跟哪些人做朋友？</Question>
        <A>A.常提出新注意的</A>
        <AType>N</AType>
        <B>B.脚踏实地的</B>
        <BType>S</BType>
    </Option>
    <Option>
        <Question>23.要作决定时，你认为比较重要的是</Question>
        <A>A.据事实衡量</A>
        <AType>T</AType>
        <B>B.考虑他人的感受和意见</B>
        <BType>F</BType>
    </Option>
    <Option>
        <Question>24.要做许多人也做的事，你比较喜欢</Question>
        <A>A.按照一般认可的方法去做</A>
        <AType>S</AType>
        <B>B.构想一个自己的想法</B>
        <BType>N</BType>
    </Option>
    <Option>
        <Question>25.在社交聚会中，你</Question>
        <A>A.有时感到郁闷</A>
        <AType>I</AType>
        <B>B.常常乐在其中</B>
        <BType>E</BType>
    </Option>
    <Option>
        <Question>26.下面哪个词语更和我心意</Question>
        <A>A.实际</A>
        <AType>T</AType>
        <B>B.多愁善感</B>
        <BType>F</BType>
    </Option>
    <Option>
        <Question>27.你通常较喜欢的科目是</Question>
        <A>A.讲授概念和原则的</A>
        <AType>N</AType>
        <B>B.讲授事实和数据的</B>
        <BType>S</BType>
    </Option>
    <Option>
        <Question>28.你是否经常让</Question>
        <A>A.你的情感支配你的理智</A>
        <AType>F</AType>
        <B>B.你的理智主宰你的情感</B>
        <BType>T</BType>
    </Option>
</QuizQuest>
