=== MixJade/JavaLearn/interest/swingTes/src/main/resources/mbti/quizQuest.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
    限制xml中，
    有一个根标签QuizQuest，
    根标签下，有许多Option标签，
    每个Option标签，有五个属性：
    分别是:quest、A、aType、B、bTYpe,
    限制aType与bType属性值，只能是F、N、M、J中的一个
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="QuizQuest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Option" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="quest" use="required" type="xs:string">
                        </xs:attribute>
                        <xs:attribute name="A" use="required" type="xs:string">
                        </xs:attribute>
                        <xs:attribute name="aType" use="required" type="xs:string">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="E"/>
                                    <xs:enumeration value="I"/>
                                    <xs:enumeration value="S"/>
                                    <xs:enumeration value="N"/>
                                    <xs:enumeration value="T"/>
                                    <xs:enumeration value="F"/>
                                    <xs:enumeration value="J"/>
                                    <xs:enumeration value="P"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="B" use="required" type="xs:string">
                        </xs:attribute>
                        <xs:attribute name="bType" use="required" type="xs:string">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="E"/>
                                    <xs:enumeration value="I"/>
                                    <xs:enumeration value="S"/>
                                    <xs:enumeration value="N"/>
                                    <xs:enumeration value="T"/>
                                    <xs:enumeration value="F"/>
                                    <xs:enumeration value="J"/>
                                    <xs:enumeration value="P"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MixJade/JavaLearn/interest/swingTes/src/main/resources/mbti/quizQuest.xml
<?xml version="1.0" encoding="UTF-8" ?>
<QuizQuest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="quizQuest.xsd">
    <Option quest="1.当你要外出一整天，你会"
            A="A.计划你要做什么和在什么时候做"
            aType="J"
            B="B.说去就去"
            bType="P"/>
    <Option quest="2.你是否"
            A="A.容易让人了解"
            aType="E"
            B="B.难于让人了解"
            bType="I"/>
    <Option quest="3.你认为自己是一个"
            A="A.较为随兴所至的人"
            aType="P"
            B="B.较为有条理的人"
            bType="J"/>
    <Option quest="4.假如你是一位老师，你会选教"
            A="A.以事实为主的课程"
            aType="S"
            B="B.涉及理论的课程"
            bType="N"/>
    <Option quest="5.处理许多事情上，你会喜欢"
            A="A.凭兴所至行事"
            aType="P"
            B="B.按照计划行事"
            bType="J"/>
    <Option quest="6.下面哪个词语更和我心意"
            A="A.仁慈慷慨的"
            aType="F"
            B="B.意志坚定的"
            bType="T"/>
    <Option quest="7.按照程序表做事，"
            A="A.合你心意"
            aType="J"
            B="B.令你感到束缚"
            bType="P"/>
    <Option quest="8.你做事多数是"
            A="A.按当天心情去做"
            aType="J"
            B="B.照拟好的程序表去做"
            bType="P"/>
    <Option quest="9.你倾向"
            A="A.重视感情多于逻辑"
            aType="F"
            B="B.重视逻辑多于感情"
            bType="T"/>
    <Option quest="10.与很多人一起会"
            A="A.令你活力培增"
            aType="E"
            B="B.常常令你心力憔悴"
            bType="I"/>
    <Option quest="11.当你有一份特别的任务，你会喜欢"
            A="A.开始前小心组织计划"
            aType="J"
            B="B.边做边找须做什么"
            bType="P"/>
    <Option quest="12.在大多数情况下，你会选择"
            A="A.顺其自然"
            aType="P"
            B="B.按程序表做事"
            bType="J"/>
    <Option quest="13.你通常"
            A="A.与人容易混熟"
            aType="E"
            B="B.比较沉静或矜持"
            bType="I"/>
    <Option quest="14.哪些人会更吸引你？"
            A="A.一个思想敏捷及非常聪颖的人"
            aType="N"
            B="B.实事求是，具丰富常识的人"
            bType="S"/>
    <Option quest="15.大多数人会说你是一个"
            A="A.重视自我隐私的人"
            aType="I"
            B="B.非常坦率开放的人"
            bType="E"/>
    <Option quest="16.在一大群人当中，通常是"
            A="A.你介绍大家认识"
            aType="E"
            B="B.别人介绍你"
            bType="I"/>
    <Option quest="17.哪个是较高的赞誉，或称许为"
            A="A.能干的"
            aType="T"
            B="B.富有同情心"
            bType="F"/>
    <Option quest="18.你喜欢花很多的时间"
            A="A.一个人独处"
            aType="I"
            B="B.合别人在一起"
            bType="E"/>
    <Option quest="19.一般来说，你和哪些人比较合得来？"
            A="A.富于想象力的人"
            aType="N"
            B="B.现实的人"
            bType="S"/>
    <Option quest="20.你宁愿被人认为是一个"
            A="A.实事求是的人"
            aType="S"
            B="B.机灵的人"
            bType="N"/>
    <Option quest="21.哪个是较高的赞誉，或称许为？"
            A="A.一贯感性的人"
            aType="F"
            B="B.一贯理性的人"
            bType="T"/>
    <Option quest="22.你会跟哪些人做朋友？"
            A="A.常提出新注意的"
            aType="N"
            B="B.脚踏实地的"
            bType="S"/>
    <Option quest="23.要作决定时，你认为比较重要的是"
            A="A.据事实衡量"
            aType="T"
            B="B.考虑他人的感受和意见"
            bType="F"/>
    <Option quest="24.要做许多人也做的事，你比较喜欢"
            A="A.按照一般认可的方法去做"
            aType="S"
            B="B.构想一个自己的想法"
            bType="N"/>
    <Option quest="25.在社交聚会中，你"
            A="A.有时感到郁闷"
            aType="I"
            B="B.常常乐在其中"
            bType="E"/>
    <Option quest="26.下面哪个词语更和我心意"
            A="A.实际"
            aType="T"
            B="B.多愁善感"
            bType="F"/>
    <Option quest="27.你通常较喜欢的科目是"
            A="A.讲授概念和原则的"
            aType="N"
            B="B.讲授事实和数据的"
            bType="S"/>
    <Option quest="28.你是否经常让"
            A="A.你的情感支配你的理智"
            aType="F"
            B="B.你的理智主宰你的情感"
            bType="T"/>
</QuizQuest>
