<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE  FileGather [
        <!ELEMENT FileGather (FileManager+)>
        <!ELEMENT FileManager (FileName,FileChineseName,Introduce)>
        <!ELEMENT FileName (#PCDATA)>
        <!ELEMENT FileChineseName (#PCDATA)>
        <!ELEMENT Introduce (#PCDATA)>
        ] >

<FileGather>
    <FileManager>
        <FileName>AttemptRegex.java</FileName>
        <FileChineseName>正则表达式</FileChineseName>
        <Introduce>用正则表达式匹配某个字符后面的字符串但不包括某个字符，以及用正则表达式检查字符串格式，用正则表达式分割替换字符串</Introduce>
    </FileManager>
    <FileManager>
        <FileName>CalculatorLayout.java</FileName>
        <FileChineseName>计算器布局</FileChineseName>
        <Introduce>计算器界面布局，有批量添加按钮(用的对象数组)</Introduce>
    </FileManager>
    <FileManager>
        <FileName>Synchrony.java</FileName>
        <FileChineseName>线程同步【两取三存】</FileChineseName>
        <Introduce>关于线程通信的synchronize,wait(),notifyAll(),notify()方法的应用</Introduce>
    </FileManager>
    <FileManager>
        <FileName>CrawlFetch.java</FileName>
        <FileChineseName>正则表达式爬取网页</FileChineseName>
        <Introduce>没有什么用，等我会了网络编程就删了</Introduce>
    </FileManager>
    <FileManager>
        <FileName>CreateThread.java</FileName>
        <FileChineseName>创造线程的三种方法</FileChineseName>
        <Introduce>分别为Callable,Thread,Runnable</Introduce>
    </FileManager>
    <FileManager>
        <FileName>DateAttempt.java</FileName>
        <FileChineseName>关于日期类与时间格式</FileChineseName>
        <Introduce>date获取当前时间;SimpleDateFormat建立对象，再通过format对时间进行格式化;还有Calendar日历类;内附"商品秒杀"的时间判断；</Introduce>
    </FileManager>
    <FileManager>
        <FileName>FileOutStreamAttempt.java</FileName>
        <FileChineseName>FileOutStream中true参数的作用</FileChineseName>
        <Introduce>加了true参数写入时不会覆盖文件</Introduce>
    </FileManager>
    <FileManager>
        <FileName>attemptXmlMap.java</FileName>
        <FileChineseName>把XML的数据给到Map</FileChineseName>
        <Introduce>有JDK11才有的一次性读取所有内容，附有一个键多个值的Map写法</Introduce>
    </FileManager>
    <FileManager>
        <FileName>InspectSynchronization.java</FileName>
        <FileChineseName>关于线程同步【出纳与会计】</FileChineseName>
        <Introduce>线程同步synchronize方法说明</Introduce>
    </FileManager>
    <FileManager>
        <FileName>JpgToBase64.java</FileName>
        <FileChineseName>把图片转化成base64格式</FileChineseName>
        <Introduce>用来把镶嵌在html文件里面，会导致html文件打开卡顿</Introduce>
    </FileManager>
    <FileManager>
        <FileName>logback.xml</FileName>
        <FileChineseName>日志的配置</FileChineseName>
        <Introduce>记载了日志的保存路径及输出格式(需要三个依赖包)</Introduce>
    </FileManager>
    <FileManager>
        <FileName>LogBackExample.java</FileName>
        <FileChineseName>日志的举例</FileChineseName>
        <Introduce>测试日志好不好用，确实好用</Introduce>
    </FileManager>
    <FileManager>
        <FileName>NumberTest.java</FileName>
        <FileChineseName>循环参数的测试</FileChineseName>
        <Introduce>循环表达式里的三条语句：第一次开始赋值，每次循环开始时询问，每次循环执行完执行自增或者自减</Introduce>
    </FileManager>
    <FileManager>
        <FileName>SimpleThreadPool.java</FileName>
        <FileChineseName>简单线程池【不推荐使用】</FileChineseName>
        <Introduce>因为其他的参数不是自己设置的，处理的任务多了容易内存溢出</Introduce>
    </FileManager>
    <FileManager>
        <FileName>SummerThreadExtends.java</FileName>
        <FileChineseName>小菜鸡的线程测试</FileChineseName>
        <Introduce>线程同一个对象，它数据是共享的；事实上，线程是对对象的操作</Introduce>
    </FileManager>
    <FileManager>
        <FileName>ThreadPool.java</FileName>
        <FileChineseName>线程池的七个参数</FileChineseName>
        <Introduce>ExecutorService常用方法: execute(Runnable command);Future submit;shutdown</Introduce>
    </FileManager>
    <FileManager>
        <FileName>TimerAttempt.java</FileName>
        <FileChineseName>定时器</FileChineseName>
        <Introduce>Schedule线程池与timer对象</Introduce>
    </FileManager>
    <FileManager>
        <FileName>AttemptMap.java</FileName>
        <FileChineseName>Map的初次尝试</FileChineseName>
        <Introduce>Map确实好用，内附两数之和</Introduce>
    </FileManager>
    <FileManager>
        <FileName>ChangeSuffix.java</FileName>
        <FileChineseName>改变后缀</FileChineseName>
        <Introduce>可以批量改变文件后缀</Introduce>
    </FileManager>
    <FileManager>
        <FileName>SaveCode.java</FileName>
        <FileChineseName>一键保存代码</FileChineseName>
        <Introduce>一键保存代码，里面关于文件的输入输出操作，关于正则表达式的运用</Introduce>
    </FileManager>
    <FileManager>
        <FileName>SaveCodeDictionary.xml</FileName>
        <FileChineseName>保存代码的字典</FileChineseName>
        <Introduce>采用DTD文档约束</Introduce>
    </FileManager>
    <FileManager>
        <FileName>HelloWorld.java</FileName>
        <FileChineseName>你好啊</FileChineseName>
        <Introduce>梦开始的地方</Introduce>
    </FileManager>
    <FileManager>
        <FileName>udpAddressAttempt.java</FileName>
        <FileChineseName>UDP的地址测试</FileChineseName>
        <Introduce>关于检查主机和网站的IP</Introduce>
    </FileManager>
    <FileManager>
        <FileName>udpClientAttempt.java</FileName>
        <FileChineseName>UDP的客户端</FileChineseName>
        <Introduce>与UDP服务端配套，多次发送，输入"exit"终止，附带发送一次的方法</Introduce>
    </FileManager>
    <FileManager>
        <FileName>udpServerAttempt.java</FileName>
        <FileChineseName>UDP的服务端</FileChineseName>
        <Introduce>与UDP客户端配套，先于客户端启动，多次接收，输入"exit"终止，附带接收一次的方法</Introduce>
    </FileManager>
    <FileManager>
        <FileName>TcpClientAttempt.java</FileName>
        <FileChineseName>Tcp客户端</FileChineseName>
        <Introduce>多次发送，输入exit终止</Introduce>
    </FileManager>
    <FileManager>
        <FileName>TcpServerAttempt.java</FileName>
        <FileChineseName>Tcp服务端</FileChineseName>
        <Introduce>与Tcp客户端配套，先与客户端启动</Introduce>
    </FileManager>
    <FileManager>
        <FileName>Interpretation01.java</FileName>
        <FileChineseName>注解、元注解的示例</FileChineseName>
        <Introduce>注解的几种形式，value、Target、Retention三种关键字</Introduce>
    </FileManager>
    <FileManager>
        <FileName>InterpretRunDemo.java</FileName>
        <FileChineseName>注解在框架的运用</FileChineseName>
        <Introduce>加了MyTest的方法才会运行</Introduce>
    </FileManager>
    <FileManager>
        <FileName>CXKProxy.java</FileName>
        <FileChineseName>动态代理</FileChineseName>
        <Introduce>代理技术可以减少重复使用的代码，并且对运行速度几乎没有影响</Introduce>
    </FileManager>
    <FileManager>
        <FileName>TestCXKProxy.java</FileName>
        <FileChineseName>单元测试框架Junit</FileChineseName>
        <Introduce>传说只要打出@Test就会召唤出的框架，不过记得写一个测试类来容纳它哦</Introduce>
    </FileManager>
    <FileManager>
        <FileName>TestXmlAnalysis.java</FileName>
        <FileChineseName>Dom4j解析</FileChineseName>
        <Introduce>dom4j解析技术，只演示了冰山一角，更多用法请看它的官方文档</Introduce>
    </FileManager>
    <FileManager>
        <FileName>TestXPath.java</FileName>
        <FileChineseName>XPath解析技术</FileChineseName>
        <Introduce>又是熟悉的XPath，跟python的差不多啊</Introduce>
    </FileManager>
    <FileManager>
        <FileName>MixFirstSql.java</FileName>
        <FileChineseName>mysql第一次尝试</FileChineseName>
        <Introduce>关于mysql的查询操作</Introduce>
    </FileManager>
    <FileManager>
        <FileName>MixSecondSql.java</FileName>
        <FileChineseName>mysql第二次尝试</FileChineseName>
        <Introduce>对于一些语句的简化，以及修改数据的语句。注：update执行DML,DCL;query执行DQL</Introduce>
    </FileManager>
    <FileManager>
        <FileName>MixThirdSql.java</FileName>
        <FileChineseName>事务的实现</FileChineseName>
        <Introduce>用connection来实现设置手动提交，提交，回滚</Introduce>
    </FileManager>
    <FileManager>
        <FileName>MixFourthSql.java</FileName>
        <FileChineseName>查询数据入集合</FileChineseName>
        <Introduce>将查询的数据放入集合，以及对于getXXX方法的一个补充</Introduce>
    </FileManager>
    <FileManager>
        <FileName>ReallySql.java</FileName>
        <FileChineseName>预编译</FileChineseName>
        <Introduce>防止sql注入的预编译，同时也简化了给sql语句传参的流程</Introduce>
    </FileManager>
    <FileManager>
        <FileName>CrudTest.java</FileName>
        <FileChineseName>增删改查大杂烩</FileChineseName>
        <Introduce>举一反三，不过似乎sql是先集中预编译，以至于耗时全部在开始</Introduce>
    </FileManager>
    <FileManager>
        <FileName>CrudUtil.java</FileName>
        <FileChineseName>工具类</FileChineseName>
        <Introduce>通过静态代码块来减少代码的重复调用</Introduce>
    </FileManager>
    <FileManager>
        <FileName>druid.properties</FileName>
        <FileChineseName>德鲁伊文件配置</FileChineseName>
        <Introduce>记得不要加引号，下面三个数，从上到下：初始线程，最大线程，最大等待时间</Introduce>
    </FileManager>
    <FileManager>
        <FileName>ReallyExtendSql.java</FileName>
        <FileChineseName>预编译的演示</FileChineseName>
        <Introduce>这里开始使用德鲁伊预编译</Introduce>
    </FileManager>
    <FileManager>
        <FileName>TwoDotDistance.java</FileName>
        <FileChineseName>两点距离</FileChineseName>
        <Introduce>计算两点之间距离</Introduce>
    </FileManager>
    <FileManager>
        <FileName>Calculator.java</FileName>
        <FileChineseName>计算加减乘除</FileChineseName>
        <Introduce>关于事件监听与处理</Introduce>
    </FileManager>
    <FileManager>
        <FileName>CalculatorTrapezoid.java</FileName>
        <FileChineseName>计算梯形面积</FileChineseName>
        <Introduce>使用MVC结构，即模型-控制器-视图</Introduce>
    </FileManager>
    <FileManager>
        <FileName>PlayFair.java</FileName>
        <FileChineseName>PlayFair加密</FileChineseName>
        <Introduce>替代字符为x，只能给字符加密</Introduce>
    </FileManager>
</FileGather>